# NeMo-RL production path (Linux + multi-GPU)
#
# Prerequisites:
#   git clone https://github.com/NVIDIA-NeMo/RL.git
#   Follow docs/NEMO_RL_SETUP.md
#
# Example:
#   cd /path/to/NeMo-RL
#   uv run examples/nemo_gym/run_grpo_nemo_gym.py \
#     --config ../nemotron-posttraining-lab/configs/nemo_rl/grpo_tiny.yaml \
#     data.train_jsonl_fpath=../nemotron-posttraining-lab/data/processed/rl_train.jsonl \
#     data.validation_jsonl_fpath=../nemotron-posttraining-lab/data/processed/rl_val.jsonl

Write-Host "See docs/NEMO_RL_SETUP.md for NeMo-RL cluster instructions."
Write-Host "Processed JSONL files are generated by scripts/prepare_datasets.py"
